# Generated by Django 6.0.5 on 2026-08-17 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الكورس/الشهر')),
                ('description', models.TextField(blank=True, verbose_name='وصف الكورس')),
                ('grade', models.CharField(choices=[('1', 'الصف الثاني الثانوي'), ('2', 'الصف الثالث الثانوي')], default='1', max_length=1, verbose_name='الصف الدراسي')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='months/thumbnails/', verbose_name='صورة الكورس')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='سعر الكورس')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر للطلاب؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'كورس/شهر',
                'verbose_name_plural': '📚 الكورسات والشهور',
                'ordering': ['grade', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TopStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='اسم الطالب المتفوق')),
                ('score_or_percentage', models.CharField(max_length=50, verbose_name='الدرجة أو النسبة')),
                ('grade', models.CharField(choices=[('1', 'الصف الثاني الثانوي'), ('2', 'الصف الثالث الثانوي')], max_length=1, verbose_name='الصف الدراسي')),
                ('image', models.ImageField(blank=True, null=True, upload_to='top_students/', verbose_name='صورة الطالب (اختياري)')),
                ('arrange', models.IntegerField(default=1, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'طالب متفوق',
                'verbose_name_plural': '🏆 لوحة الأوائل',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المحاضرة')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='رابط فيديو المحاضرة')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lectures_pdf/', verbose_name='ملف PDF للمحاضرة')),
                ('order', models.IntegerField(default=1, verbose_name='ترتيب المحاضرة')),
                ('is_individual', models.BooleanField(default=False, verbose_name='محاضرة منفصلة؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='core.month', verbose_name='التابع لكورس')),
            ],
            options={
                'verbose_name': 'محاضرة',
                'verbose_name_plural': '🎥 المحاضرات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الامتحان')),
                ('is_comprehensive', models.BooleanField(default=False, verbose_name='امتحان شامل؟')),
                ('duration_mins', models.IntegerField(default=30, verbose_name='مدة الامتحان بالدقائق')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='core.lecture', verbose_name='تابع لمحاضرة (اختياري)')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.month', verbose_name='التابع لكورس')),
            ],
            options={
                'verbose_name': 'امتحان',
                'verbose_name_plural': '📝 الامتحانات',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions_images/', verbose_name='صورة مع السؤال (اختياري)')),
                ('choice1', models.CharField(max_length=255, verbose_name='الاختيار الأول')),
                ('choice2', models.CharField(max_length=255, verbose_name='الاختيار الثاني')),
                ('choice3', models.CharField(max_length=255, verbose_name='الاختيار الثالث')),
                ('choice4', models.CharField(max_length=255, verbose_name='الاختيار الرابع')),
                ('correct_answer', models.CharField(choices=[('1', 'الاختيار الأول'), ('2', 'الاختيار الثاني'), ('3', 'الاختيار الثالث'), ('4', 'الاختيار الرابع')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.exam', verbose_name='الامتحان')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': '❓ الأسئلة',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم تليفون الطالب')),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم تليفون ولي الأمر')),
                ('system', models.CharField(choices=[('general', 'عام'), ('azhari', 'أزهري'), ('baccalaureate', 'بكالوريا')], default='general', max_length=20, verbose_name='النظام التعليمي')),
                ('governorate', models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة')),
                ('grade', models.CharField(choices=[('1', 'الصف الثاني الثانوي'), ('2', 'الصف الثالث الثانوي')], default='1', max_length=1, verbose_name='الصف الدراسي')),
                ('streak', models.IntegerField(default=0, verbose_name='أيام متتالية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بروفايل الطالب',
                'verbose_name_plural': '👤 بروفايل الطلاب',
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, verbose_name='اسم الكورس / الامتحان')),
                ('score', models.CharField(max_length=50, verbose_name='الدرجة')),
                ('attended_lessons', models.IntegerField(default=0, verbose_name='المحاضرات المحضورة')),
                ('remaining_lessons', models.IntegerField(default=0, verbose_name='المحاضرات المتبقية')),
                ('status', models.CharField(default='جاري', max_length=50, verbose_name='الحالة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'نتيجة ومتابعة الطالب',
                'verbose_name_plural': '📊 لوحة متابعة النتائج',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعّل؟')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.lecture', verbose_name='المحاضرة الفردية (اختياري)')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.month', verbose_name='الكورس المشترك فيه')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': '💳 اشتراكات الطلاب',
            },
        ),
    ]
