# Generated by Django 6.0.5 on 2026-05-12 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المحاضرة')),
                ('video_url', models.URLField(verbose_name='رابط الفيديو (YouTube/Vimeo)')),
                ('content', models.TextField(blank=True, verbose_name='وصف أو محتوى الحصة')),
                ('is_individual', models.BooleanField(default=False, verbose_name='تفعيل فردي (للحالات الخاصة)')),
                ('individual_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='سعر التفعيل الفردي')),
            ],
            options={
                'verbose_name': 'محاضرة',
                'verbose_name_plural': 'المحاضرات',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الشهر / الكورس')),
                ('description', models.TextField(blank=True, verbose_name='وصف الشهر')),
                ('image', models.ImageField(upload_to='months/', verbose_name='صورة الغلاف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='سعر الشهر الكامل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'الشهور',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='رقم تليفون الطالب')),
                ('parent_phone', models.CharField(blank=True, max_length=15, verbose_name='رقم تليفون ولي الأمر')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'بروفايل طالب',
                'verbose_name_plural': 'بروفايلات الطلاب',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='تم الدفع / مفعل')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.month', verbose_name='الشهر')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='lecture',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='core.month', verbose_name='تابع لشهر'),
        ),
    ]
