# Generated by Django 6.0.5 on 2026-05-12 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lecture_month_studentprofile_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الامتحان')),
                ('is_comprehensive', models.BooleanField(default=False, verbose_name='هل هو امتحان شامل؟')),
                ('duration_mins', models.IntegerField(default=30, verbose_name='مدة الامتحان بالدقائق')),
                ('lecture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='core.lecture', verbose_name='تابع لمحاضرة (اختياري)')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_exams', to='core.month', verbose_name='امتحان شامل لشهر (اختياري)')),
            ],
            options={
                'verbose_name': 'امتحان',
                'verbose_name_plural': 'الامتحانات',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='صورة للسؤال (اختياري)')),
                ('choice1', models.CharField(max_length=200, verbose_name='الاختيار الأول')),
                ('choice2', models.CharField(max_length=200, verbose_name='الاختيار الثاني')),
                ('choice3', models.CharField(max_length=200, verbose_name='الاختيار الثالث')),
                ('choice4', models.CharField(max_length=200, verbose_name='الاختيار الرابع')),
                ('correct_answer', models.IntegerField(choices=[(1, 'الأول'), (2, 'الثاني'), (3, 'الثالث'), (4, 'الرابع')], verbose_name='الإجابة الصحيحة')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.exam', verbose_name='الامتحان')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
            },
        ),
    ]
