# Generated by Django 6.0.5 on 2026-05-20 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exam_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الكورس')),
                ('description', models.TextField(blank=True, verbose_name='وصف الكورس')),
                ('grade', models.CharField(choices=[('1', 'الصف الأول الثانوي'), ('2', 'الصف الثاني الثانوي'), ('3', 'الصف الثالث الثانوي')], max_length=1, verbose_name='الصف الدراسي الموجه له')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'كورس',
                'verbose_name_plural': '📚 الكورسات التعليمية',
            },
        ),
        migrations.CreateModel(
            name='TopStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='اسم الطالب المتفوق')),
                ('score_or_percentage', models.CharField(max_length=50, verbose_name='الدرجة أو النسبة (مثال: 99%)')),
                ('grade', models.CharField(choices=[('1', 'الصف الأول الثانوي'), ('2', 'الصف الثاني الثانوي'), ('3', 'الصف الثالث الثانوي')], max_length=1, verbose_name='الصف الدراسي')),
                ('image', models.ImageField(blank=True, null=True, upload_to='top_students/', verbose_name='صورة الطالب (اختياري)')),
                ('arrange', models.IntegerField(default=1, verbose_name='الترتيب (1 للأول، 2 للثاني...)')),
            ],
            options={
                'verbose_name': 'طالب متفوق',
                'verbose_name_plural': '🏆 لوحة الأوائل (الصفحة الرئيسية)',
            },
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'امتحان', 'verbose_name_plural': '📝 الامتحانات'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': 'محاضرة', 'verbose_name_plural': '🎥 المحاضرات'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name': 'الشهر الدراسي', 'verbose_name_plural': '📅 الشهور الدراسية'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'سؤال', 'verbose_name_plural': '❓ الأسئلة'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'بروفايل الطالب', 'verbose_name_plural': '👤 بروفايل الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'اشتراك', 'verbose_name_plural': '💳 اشتراكات الطلاب'},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='individual_price',
        ),
        migrations.RemoveField(
            model_name='month',
            name='description',
        ),
        migrations.RemoveField(
            model_name='month',
            name='image',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='lecture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الرفع'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures_pdf/', verbose_name='ملف PDF للمحاضرة'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='governorate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(choices=[('1', 'الصف الأول الثانوي'), ('2', 'الصف الثاني الثانوي'), ('3', 'الصف الثالث الثانوي')], default='1', max_length=1, verbose_name='الصف الدراسي'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='system',
            field=models.CharField(default='general', max_length=20, verbose_name='النظام التعليمي'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_comprehensive',
            field=models.BooleanField(default=False, verbose_name='هل هو امتحان شامل على الشهر كامل؟'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='core.lecture', verbose_name='تابع لمحاضرة معينة (إختياري)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.month', verbose_name='التابع لشهر'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='is_individual',
            field=models.BooleanField(default=False, verbose_name='هل هي محاضرة منفصلة (خارج الشهر)؟'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='core.month', verbose_name='التابع لشهر'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط فيديو المحاضرة'),
        ),
        migrations.AlterField(
            model_name='month',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='month',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='سعر الشهر'),
        ),
        migrations.AlterField(
            model_name='month',
            name='title',
            field=models.CharField(max_length=100, verbose_name='اسم الشهر'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.CharField(max_length=255, verbose_name='الاختيار الأول'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.CharField(max_length=255, verbose_name='الاختيار الثاني'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.CharField(max_length=255, verbose_name='الاختيار الثالث'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4',
            field=models.CharField(max_length=255, verbose_name='الاختيار الرابع'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('1', 'الاختيار الأول'), ('2', 'الاختيار الثاني'), ('3', 'الاختيار الثالث'), ('4', 'الاختيار الرابع')], max_length=1, verbose_name='الإجابة الصحيحة'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions_images/', verbose_name='صورة مع السؤال (إختياري)'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم تليفون ولي الأمر'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='رقم تليفون الطالب'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='حالة التفعيل (نشط أم لا)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.month', verbose_name='الشهر المشترك فيه'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك'),
        ),
    ]
