# Generated by Django 6.0.5 on 2026-05-22 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_topstudent_alter_exam_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, verbose_name='اسم الكورس / الامتحان')),
                ('score', models.CharField(max_length=50, verbose_name='الدرجة')),
                ('attended_lessons', models.IntegerField(default=0, verbose_name='المحاضرات المحضورة')),
                ('remaining_lessons', models.IntegerField(default=0, verbose_name='المحاضرات المتبقية')),
                ('status', models.CharField(default='جاري', max_length=50, verbose_name='الحالة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'نتيجة ومتابعة الطالب',
                'verbose_name_plural': '📊 لوحة متابعة النتائج',
            },
        ),
    ]
