# Generated by Django 6.0.5 on 2026-05-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='streak',
            field=models.IntegerField(default=0, verbose_name='أيام متتالية'),
        ),
    ]
