# Generated by Django 6.0.5 on 2026-05-24 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studentprofile_streak'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='سعر الكورس'),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='صورة الكورس (اختياري)'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='عدد الساعات'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_videos',
            field=models.IntegerField(default=0, verbose_name='عدد الفيديوهات'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعّل؟')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('watched_videos', models.IntegerField(default=0, verbose_name='فيديوهات تمت مشاهدتها')),
                ('watched_minutes', models.IntegerField(default=0, verbose_name='دقائق المشاهدة')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.course', verbose_name='الكورس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل في كورس',
                'verbose_name_plural': '🎓 تسجيلات الطلاب في الكورسات',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
