# Generated by Django 6.0.5 on 2026-05-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_price_course_thumbnail_course_total_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['order', 'id'], 'verbose_name': 'محاضرة', 'verbose_name_plural': '🎥 المحاضرات'},
        ),
        migrations.AddField(
            model_name='lecture',
            name='order',
            field=models.IntegerField(default=1, verbose_name='ترتيب المحاضرة'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='is_individual',
            field=models.BooleanField(default=False, verbose_name='محاضرة منفصلة؟'),
        ),
    ]
