# Generated by Django 6.0.5 on 2026-05-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_lecture_options_lecture_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='grade',
            field=models.CharField(choices=[('1', 'الصف الأول الثانوي'), ('2', 'الصف الثاني الثانوي'), ('3', 'الصف الثالث الثانوي')], default='1', max_length=1, verbose_name='الصف الدراسي'),
        ),
    ]
