# Generated by Django 6.0.5 on 2026-05-26 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_month_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['grade', 'title'], 'verbose_name': 'كورس/شهر', 'verbose_name_plural': '📚 الكورسات والشهور'},
        ),
        migrations.AlterModelOptions(
            name='topstudent',
            options={'verbose_name': 'طالب متفوق', 'verbose_name_plural': '🏆 لوحة الأوائل'},
        ),
        migrations.AddField(
            model_name='month',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الكورس'),
        ),
        migrations.AddField(
            model_name='month',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ظاهر للطلاب؟'),
        ),
        migrations.AddField(
            model_name='month',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='months/thumbnails/', verbose_name='صورة الكورس'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_comprehensive',
            field=models.BooleanField(default=False, verbose_name='امتحان شامل؟'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='core.lecture', verbose_name='تابع لمحاضرة (اختياري)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.month', verbose_name='التابع لكورس'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='core.month', verbose_name='التابع لكورس'),
        ),
        migrations.AlterField(
            model_name='month',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='month',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='سعر الكورس'),
        ),
        migrations.AlterField(
            model_name='month',
            name='title',
            field=models.CharField(max_length=200, verbose_name='اسم الكورس/الشهر'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions_images/', verbose_name='صورة مع السؤال (اختياري)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='مفعّل؟'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.month', verbose_name='الكورس المشترك فيه'),
        ),
        migrations.AlterField(
            model_name='topstudent',
            name='arrange',
            field=models.IntegerField(default=1, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='topstudent',
            name='score_or_percentage',
            field=models.CharField(max_length=50, verbose_name='الدرجة أو النسبة'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('student', 'month')},
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
