# Generated by Django 6.0.5 on 2026-07-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_subscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='grade',
            field=models.CharField(choices=[('1', 'الصف الثاني الثانوي'), ('2', 'الصف الثالث الثانوي')], default='1', max_length=1, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(choices=[('1', 'الصف الثاني الثانوي'), ('2', 'الصف الثالث الثانوي')], default='1', max_length=1, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='topstudent',
            name='grade',
            field=models.CharField(choices=[('1', 'الصف الثاني الثانوي'), ('2', 'الصف الثالث الثانوي')], max_length=1, verbose_name='الصف الدراسي'),
        ),
    ]
