# Generated by Django 6.0.5 on 2026-08-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_month_grade_alter_studentprofile_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='system',
            field=models.CharField(choices=[('general', 'عام'), ('azhari', 'أزهري'), ('baccalaureate', 'بكالوريا')], default='general', max_length=20, verbose_name='النظام التعليمي'),
        ),
    ]
